services:
  db:
    image: mysql:8.3.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'academy-db'
      MYSQL_USER: 'academy-user'
      MYSQL_PASSWORD: 'academy-password'
      MYSQL_ROOT_PASSWORD: 'academy-root-password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: